# Fisher add in 4/01
# university route

sylius_backend_university_index:
    pattern: /
    methods: [GET]
    defaults:
         _controller: sylius.controller.university:indexAction
         _sylius:
             template: SyliusWebBundle:Backend/University:index.html.twig
             sortable: true

sylius_backend_university_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
         _controller: sylius.controller.university:createAction
         _sylius:
             template: SyliusWebBundle:Backend/University:create.html.twig
             redirect: sylius_backend_university_show

sylius_backend_university_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
         _controller: sylius.controller.university:updateAction
         _sylius:
             template: SyliusWebBundle:Backend/University:update.html.twig
             redirect: sylius_backend_university_show

sylius_backend_university_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
         _controller: sylius.controller.university:deleteAction
         _sylius:
             template: SyliusWebBundle:Backend/Misc:delete.html.twig
             redirect: sylius_backend_university_index

sylius_backend_university_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.university:showAction
        _sylius:
            template: SyliusWebBundle:Backend/University:show.html.twig


